# Generated by Django 5.0.6 on 2025-12-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Mã hóa đơn",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Mô tả"),
                ),
                ("image", models.ImageField(upload_to="images/", verbose_name="Ảnh")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
            ],
            options={
                "verbose_name": "Hóa đơn",
                "verbose_name_plural": "Hóa đơn",
                "ordering": ["-created_at"],
            },
        ),
    ]
