# Generated by Django 6.0 on 2025-12-20 11:12

from django.db import migrations, models


def remove_prefix_from_receipt_image(apps, schema_editor):  # noqa: ARG001
    Receipt = apps.get_model("app", "Receipt")
    for receipt in Receipt.objects.all():
        if receipt.image and receipt.image.name.startswith("images/"):
            receipt.image.name = receipt.image.name.removeprefix("images/")
            receipt.save()


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Đã xoá"),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="Ảnh"),
        ),
        migrations.RunPython(
            remove_prefix_from_receipt_image,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
