# Generated by Django 5.0.6 on 2025-08-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_product_options_alter_product_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="images/", verbose_name="Ảnh mã số thuế"),
        ),
    ]
