# Generated by Django 5.0.6 on 2025-12-18 06:22

from django.db import migrations, models


def upper_code(apps, schema_editor):  # noqa: ARG001
    Receipt = apps.get_model("app", "Receipt")
    for receipt in Receipt.objects.all():
        receipt.code = receipt.code.upper()
        receipt.save()


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_product_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product",
            new_name="Receipt",
        ),
        migrations.RenameField(
            model_name="receipt",
            old_name="tax_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="receipt",
            old_name="product_name",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="receipt",
            name="code",
            field=models.CharField(
                max_length=100,
                unique=True,
                verbose_name="Mã hóa đơn",
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="description",
            field=models.TextField(default="", verbose_name="Mô tả"),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="image",
            field=models.ImageField(upload_to="images/", verbose_name="Ảnh"),
        ),
        migrations.AlterModelOptions(
            name="receipt",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Hóa đơn",
                "verbose_name_plural": "Hóa đơn",
            },
        ),
        migrations.AlterField(
            model_name="receipt",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Mô tả"),
        ),
        migrations.RunPython(code=upper_code, reverse_code=migrations.RunPython.noop),
    ]
