# Generated by Django 6.0 on 2025-12-23 09:43

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, verbose_name="Mã hóa đơn")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Mô tả"),
                ),
                ("image", models.ImageField(upload_to="", verbose_name="Ảnh")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Đã xóa"),
                ),
            ],
            options={
                "verbose_name": "Hóa đơn",
                "verbose_name_plural": "Hóa đơn",
                "db_table": "receipts",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.comparison.Collate("code", "NOCASE"),
                        condition=models.Q(("is_deleted", False)),
                        name="uniq_receipt_code_nocase",
                    ),
                ],
            },
        ),
    ]
